### ISSUE TITLE
Labels and markers are misaligned on mobile

### ISSUE THREAD

**Issue by FrederikNS** [FrederikNS/gw2map#1]

**Comment by m-decoster** [comment]
This also seems to be the case on Safari, Chrome and Firefox on OS X.

**Comment by FrederikNS** [comment]
Hmm, odd, It works nicely in Chrome and Firefox on both Linux and Windows

**Comment by m-decoster** [comment]
That might be it. The map starts zoomed out in the top left corner of the screen. It's probably a Retina issue then.

**Comment by FrederikNS** [comment]
I removed the Retina detection, which fixed the problem on my mobile phone. Did it also work for you?

**Comment by m-decoster** [comment]
It seems to be working now, yes.

**Comment by FrederikNS** [comment]
Super, I'll close this issue then
